version: '3.8'

services:
  globetrotter-bff:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - services.travel.url=http://globetrotter-services:8080
      - services.openai.url=http://globetrotter-services:8080
    restart: unless-stopped
