spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:sk-demo-key}
      model: ${OPENAI_MODEL:gpt-3.5-turbo}
    mcp:
      client:
        sse:
          connections:
            globetrotter-mcp-server:
              url: http://globetrotter-mcp-server:8082

logging:
  level:
    root: INFO
    com.globetrotter.bff: ${LOGGING_LEVEL_COM_GLOBETROTTER_BFF:INFO}
    com.globetrotter.bff.controller.TravelController: ${LOGGING_LEVEL_COM_GLOBETROTTER_BFF_CONTROLLER_TRAVELCONTROLLER:INFO}
    org.springframework.web: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB:INFO}
    org.springframework.ai: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_AI:INFO}
    org.springframework.boot: INFO
    org.springframework.ai.autoconfigure.mcp: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_AI_AUTOCONFIGURE_MCP:INFO}
    io.modelcontextprotocol: ${LOGGING_LEVEL_IO_MODELCONTEXTPROTOCOL:INFO}

server:
  port: 8084

# Debug configuration
debug: ${DEBUG:false}

# OpenAPI documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
