server:
  port: 8081

spring:
  application:
    name: globetrotter-bff
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 90000
    circuitbreaker:
      resilience4j:
        enabled: true

# Services configuration
services:
  travel:
    url: http://globetrotter-services:8080
  openai:
    url: http://globetrotter-services:8080

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# OpenAPI documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
